# Site settings
title: Ben Kammerling
tagline: Web Developer
email: hi@benkammerling.com
description: > # this means to ignore newlines until "baseurl:"
  Web developer, cyclist, traveller, lover of food, permanently confused
  about life and one's purpose on this giant spinning greeny-blue ball. This
  is my online web space and all are welcome.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://benkammerling.github.io" # the base hostname & protocol for your site
twitter_username: bkammerling
github_username:  bkammerling
instagram_username: bkammerling
linkedin_username: bkammerling

# Build settings
markdown: kramdown
