# Site
name: "Ben Kammerling"
title: "Ben Kammerling - Tech Guy"
description: "Exploring the fabulous world of web tech, for humans and business. Maybe some travel & food too!"
logo: 'assets/images/logo-3d.svg'
favicon: 'assets/images/logo-3d.png'
baseurl: ""
google_analytics: 'UA-46634104-2'
include: ["_pages"]
permalink: /:title/
email: hi@benkammerling.com
image: assets/images/social-image.png

# Authors
authors:
  ben:
    name: Ben
    display_name: Ben
    gravatar: 41620ba1d1acb7bbe44682aa171186ad
    email: hi@benkammerling.com
    web: http://www.benkammerling.com/
    instagram: https://instagram.com/bkammerling
    github: https://github.com/bkammerling
    description: "Web enthusiast, passionate about making digital experiences more human and more fun!"
  john:
    name: John
    display_name: John
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
